PATCH http://localhost:8080/exchangeRate/USDEUR
Content-Type: application/x-www-form-urlencoded

rate=1.2

#POST http://localhost:8080/currencies
#Content-Type: application/x-www-form-urlencoded
#
#name=EUROO&code=EUS
